import { ApiProperty } from '@nestjs/swagger';
import { IUserEntity } from 'src/users/entities/user.entity';


export class LoginResponseDto {
  @ApiProperty({
    description: 'JWT generated by token',
    example: 'TOKEN_AUTOMATICALY_GENERATED',
  })
  token: string;

  @ApiProperty({
    description: 'Users data authenticated',
  })
  user: IUserEntity;
}
